language: rust
cache: cargo
sudo: false

INSTALL_DEPS: &INSTALL_DEPS
  - rustup default nightly
  - rustup target add wasm32-unknown-unknown
    # Install WASM bindgen CLI
  - curl -OL https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.23/wasm-bindgen-0.2.23-x86_64-unknown-linux-musl.tar.gz
  - tar xf wasm-bindgen-0.2.23-x86_64-unknown-linux-musl.tar.gz
  - chmod +x wasm-bindgen-0.2.23-x86_64-unknown-linux-musl/wasm-bindgen
  - mv wasm-bindgen-0.2.23-x86_64-unknown-linux-musl/wasm-bindgen ~/.cargo/bin/
  # Install Node.js
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install v10.5
  # Install Geckodriver
  - curl --retry 5 -LO https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar xf geckodriver-v0.21.0-linux64.tar.gz

matrix:
  include:
    # Tests pass on nightly
    # TODO: Separate job for JSDOM WebAssembly tests and Rust unit tests
    - rust: nightly
      env: JOB=test-everything
      before_install: *INSTALL_DEPS
      install:
        - npm install
      script:
        - GECKODRIVER=$(pwd)/geckodriver ./test.sh

    # Build documentation for the gh-pages branch
    - rust: nightly
      env: JOB=book-build-and-deploy
      cache:
        directories:
          - $HOME/.cargo
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.1" mdbook)
        - cargo install-update -a
      script:
        - (cd book && mdbook build)
        - cargo doc --no-deps -p virtual-dom-rs -p css-rs-macro
        - mv target/doc book/book/api
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        local-dir: book/book
        keep-history: false
      if: branch = master

notifications:
  email:
    on_success: never
