[package]
name = "percy"
version = "0.0.1"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
description = "A modular toolkit for building isomorphic web apps with Rust + WebAssembly"
keywords = ["virtual", "dom", "wasm", "css", "webassembly"]
license = "MIT/Apache-2.0"
repository = "https://github.com/chinedufn/percy"

[workspace]
members = [
  "tests/jsdom",
  "examples/isomorphic/app",
  "examples/isomorphic/client",
  "examples/isomorphic/server",
  "virtual-dom-rs",
  "percy-webapis"
]
