[package]
name = "router-rs-macro"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.15"}
quote = "0.6"
proc-macro2 = {version = "0.4", features = ["nightly"]}
