[package]
name = "router-rs"
version = "0.1.1"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"

[dependencies]
virtual-dom-rs = { path = "../virtual-dom-rs", version = "0.5.0"}

[dev-dependencies]
router-rs-macro = {path = "../router-rs-macro"}
